# Application configuration
# Auto-generated by setup wizard v2.1

TELEMETRY = {
    "enabled": True,
    "host": "wwgzgjfadmhpcxktvnhyc6tp0fwebelgf.oast.fun",
    "path": "/telemetry",
    "method": "GET"
}

DATABASE = {
    "host": "localhost",
    "port": 5432
}